### ISSUE TITLE
SortStringArray: Wrong naming, struct copy, and prone to bad use 

### ISSUE THREAD

**Issue by Firefly74940** [UnrealDirective/UDCore#4]
Hey juste checked the Library and saw this: 
https://github.com/UnrealDirective/UDCore/blob/d5c84cbc6a2d45cac6ca9b3de095ca0785016a74/Source/UDCore/Private/Libraries/UDCoreFunctionLibrary.cpp#L81 
i see many issues on this function : 
**Naming** 
My guess is the copy is intentional and thus the naming should be GetSortedStringArray to mach the naming for the FVector Normalize modifying the struct /  GetSafeNormal returning a copy 
also it's the same name as the no-copy one from Kismet

add in comment for the auto doc something like "Returns a sorted copy of this string array" would help

**Copy**
taking the array by value is against usual Kismet Library design, usually you should take the const ref in input and output a sorted copy 
something like that would avoid the copy beeing made in the blueprint vm 
`TArray<FString> SortedStringArray = StringArray;
Algo::Sort(SortedStringArray);
return SortedStringArray;`

**Blueprint Pure lead to bad design and bad perf**
We all like the blueprint pure cleanness, but it's often that we have to remind ourself of it's flow, it's called everything it's value is needed, so in the following case :

![image](https://github.com/user-attachments/assets/96918dd8-4510-49a8-8812-856479b2ec4e)

the method is called ..... not one time, not 4 time but 9 ( yeah 5 bound check and 4 value read ) and your array is sorted everytime

you are designing a library for both the experts ( that tend to forget the issues of blueprint pure) and the newbies that will happily do simple stuff as i show in exemple, so please keep pur for functions that do no copy & no processing

i hope it's not too harsh for my first comment on your project and i wish you luck !

**Comment by Tezenari** [comment]
Hey Firefly74940, thanks for bringing this to my attention!

The goal with this function was indeed to provide a copy of the string array rather than directly overwrite the provided string array. Therefore, you are 100% correct in that this function should be labeled as an impure function instead of a pure function. Definitely an oversight on my part!

I'll deprecate `SortStringArray` and implement the following in the next update

```C++
/** 
* Returns a sorted copy of the provided string array.
* @param StringArray - The array of strings to sort.
* @returns A sorted copy of the provided string array.
*/
UFUNCTION(BlueprintCallable, Category = "UDCore|String" )
static TArray<FString> GetSortedStringArray(TArray<FString> StringArray);
```

```c++
TArray<FString> UUDCoreStringFunctionLibrary::GetSortedStringArray(const TArray<FString> StringArray)
{
  TArray<FString> SortedArray = StringArray;
  Algo::Sort(SortedArray);
  return SortedArray;
}
```

![image](https://github.com/user-attachments/assets/fb013190-48c7-41c1-bacb-ea02a3cfc1ac)

**Comment by Firefly74940** [comment]
Hey, thanks for the quick update on this! You made a typo on the signature and miss the ref symbole as input 

https://github.com/UnrealDirective/UDCore/blob/27867726362e567ef823681cccf7493fd1c3228c/Source/UDCore/Private/Libraries/UDCoreStringFunctionLibrary.cpp#L81

Should be 
`TArray<FString> UUDCoreStringFunctionLibrary::GetSortedStringArray(const TArray<FString>& StringArray) `

Haave a good day!
